### ISSUE TITLE
Guards React to Equipped Camera as a Weapon

### ISSUE THREAD

**Issue by luxmanifestus** [glacier-modding/H3-Community-Patches#120] opened 2024-07-05 15:20 UTC
When passing by a guard with the camera equipped, they will react as if you are carrying a weapon saying things like, "Hey, put that away," etc. It's gets old. It certainly happens during a showdown; not sure if it happens on the other missions.

**Comment by Ocean-Minnow** [comment] 2024-07-05 15:21
Duplicate of #119

**Closed by Ocean-Minnow** 2024-07-05 15:21 UTC
