### ISSUE TITLE
Summer Sightseeing Suit Clipping Issue

### ISSUE THREAD

**Issue by begexq** [glacier-modding/H3-Community-Patches#146] opened 2024-08-15 23:23 UTC
On the Summer Sightseeing Suit and its Gloved equivalent, the sunglasses clip just around 47's brow.

**Comment by Ocean-Minnow** [comment] 2024-08-16 02:38
Noting here that this is **not** a duplicate of #53 since that one related to the Summer Suave suit, which is a different but similarly named suit.

This should be an easy enough fix, we'll just need to change the coordinates of the sunglasses. I'm currently very busy, but I'll see if I have time if nobody else gets it first :]

**Comment by dribbleondo** [comment] 2024-08-20 18:42
I can do this in 30 seconds. Hold on.

**Comment by Ocean-Minnow** [comment] 2024-09-15 20:22
Did this get finished? I can't remember. No PR was linked automatically but I'd like to close this if it's already done.

**Comment by VoodooHillbilly** [comment] 2024-10-09 05:15
PR #159 fixed the bug and has been merged. So this issue can be closed.

**Closed** 2024-10-09 07:50 UTC
